FROM webhippie/alpine:latest-arm32v6

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="Archiver" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

ENTRYPOINT ["/usr/bin/zip"]

RUN apk update && \
  apk upgrade && \
  apk add make zip tar gzip unrar git sed && \
  rm -rf /var/cache/apk/*
